# Generated by Django 5.1.6 on 2025-12-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mohamed Ayman', max_length=100)),
                ('title', models.CharField(default='AI & ML Engineer', max_length=100)),
                ('bio', models.TextField(default='AI Engineer and Data Scientist specializing in Machine Learning.')),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile/')),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('email_link', models.EmailField(blank=True, max_length=254)),
                ('cv_link', models.URLField(blank=True, help_text='Link to your resume PDF')),
            ],
        ),
    ]
