# Generated by Django 5.1.6 on 2026-04-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projectcategory_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(help_text='e.g., Google, AWS, Coursera', max_length=200)),
                ('category', models.CharField(choices=[('certificate', 'Certificate'), ('achievement', 'Achievement')], default='certificate', max_length=20)),
                ('date_earned', models.DateField(help_text='Date the certificate/achievement was earned')),
                ('description', models.TextField(blank=True, help_text='Brief description of what this credential covers')),
                ('credential_id', models.CharField(blank=True, help_text='Credential ID if available', max_length=200)),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify the credential')),
                ('badge_image', models.ImageField(blank=True, help_text='Badge or logo image', upload_to='certificates/')),
            ],
            options={
                'ordering': ['-date_earned'],
            },
        ),
    ]
